# NumPy Arrays

#### Python lists and numpy array are different data types

In [109]:
import numpy as np

In [110]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [111]:
#similar to range function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
# array of zeros
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [113]:
# array of ones
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [114]:
# equaly spaced points
np.linspace(1,4.5,10)

array([1.        , 1.38888889, 1.77777778, 2.16666667, 2.55555556,
       2.94444444, 3.33333333, 3.72222222, 4.11111111, 4.5       ])

In [257]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array of random number

### Method 1
This populates using random sample from a uniform distribution

NOTE: don't need to pass tuple for dimetions

In [116]:
np.random.rand(3)

array([0.49686775, 0.82871867, 0.5378264 ])

In [117]:
np.random.rand(3,2)

array([[0.57770616, 0.64851531],
       [0.62067388, 0.16452836],
       [0.67459384, 0.98246297]])

### Method 2 
This populates from the standard normal distribution or a Gaussian distribution

NOTE: don't need to pass tuple for dimetions

In [118]:
np.random.randn(3)

array([ 0.05539854, -0.35409971, -2.01289036])

In [119]:
np.random.randn(2,3)

array([[ 0.23971339, -1.37716768,  1.4243735 ],
       [-0.02555992, -1.4819882 , -0.32777259]])

### Method 3
This populates with random integers

(start, end, range)

NOTE: the output will be exclusive of end

In [120]:
np.random.randint(1,5,3)

array([1, 3, 1])

In [121]:
np.random.randint(1,10,(3,4))

array([[9, 9, 8, 3],
       [7, 1, 9, 6],
       [1, 1, 1, 8]])

### Reshaping array

In [122]:
arr = np.random.randint(1,50,10)
arr

array([47, 39, 16, 13, 44,  2, 25, 19, 24, 34])

Lenght of old array should be equal to the number of elements in the new array

NOTE: reshape method doesn't change the old arrya , it creates a new array

In [123]:
newarr = arr.reshape(2,5)
newarr

array([[47, 39, 16, 13, 44],
       [ 2, 25, 19, 24, 34]])

### Few other useful methods

In [124]:
arr = np.random.randint(1,100,10)
arr

array([39, 94, 33, 22, 82, 64, 25, 42, 94, 82])

Finding the min and max element in an arry

In [125]:
arr.max()

94

In [126]:
arr.min()

22

Finding the argument of max and min element

In [127]:
arr.argmax()

1

In [128]:
arr.argmin()

3

In [129]:
newarr = arr.reshape(2,5)
newarr

array([[39, 94, 33, 22, 82],
       [64, 25, 42, 94, 82]])

Finding shape of array

In [130]:
arr.shape

(10,)

In [134]:
newarr.shape

(2, 5)

Finding the datatype of elements in numpy array

In [246]:
arr.dtype

dtype('int64')

True if array elements satisfy the condition else false

In [253]:
arr = np.random.randint(1,100,5)
print(arr)
boolarr1 = arr > 50
print(boolarr1)
boolarr2 = arr < 50
print(boolarr2)
boolarr3 = arr %2 == 0
print(boolarr3)

[81 43 25  1  6]
[ True False False False False]
[False  True  True  True  True]
[False False False False  True]


Return array with elements which satisfy the condition

In [258]:
arr = np.random.randint(1,100,5)
print(arr)
arr[arr > 50]

[37 33 94 21 50]


array([94])

## Numpy Indexing and Selection

In [155]:
arr = np.arange(0,10,1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
arr[5]

5

In [157]:
arr[-1]

9

In [158]:
arr[1:3]

array([1, 2])

In [159]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Broadcasting

In [179]:
arr[0:5] = 10
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

## An interesiting observation

In [189]:
## numpy array

arr = np.arange(0,10,1)

s = arr[0:3]
s[0]=100
arr[1]=100
print(s)
print(arr)

[100 100   2]
[100 100   2   3   4   5   6   7   8   9]


In [190]:
# python list

x = [1,2,3,4]

e= x[0:2]
e[0]=10
print(e)
print(x)

[10, 2]
[1, 2, 3, 4]


When we assign a slice of an numpy array to another varible, but doesn't creates a copy. It references to the old array so any changes in the slice variable will show in the original array and vice versa.

This doesn't occur in python list as it creates a copy while assigning a slice to anothor variable

numpy does this to avoid memory problems while dealing with large arrays

Here is what we can do to creating a copy

In [193]:
arr = np.arange(0,10,1)

s = arr[0:3].copy()
s[0]=100
arr[1]=100
print(s)
print(arr)

[100   1   2]
[  0 100   2   3   4   5   6   7   8   9]


### Acessing elements in multidimentional array

This method can be used too other that the conventional method

In [225]:
arr2d = np.arange(1,13,1).reshape(3,4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [226]:
arr2d[-1,-1]

12

In [231]:
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

## Array operations

The following operations are present in both python list and numpy array

In [287]:
arr = np.arange(1,11,1)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [288]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [289]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [290]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

NOTE: Take care of not dividing a number by zero

In [291]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In case of python list you will get an error, but in case of numpy list numpy will not throw any error. It will just give a warning and still show output.

In [292]:
arr/0

/home/pseudorandomguy/.local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [305]:
arr**(1/2)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

<b>These operation are provided by numpy library</b>

In [300]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [301]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [304]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])